### ISSUE TITLE
gstreamer needs manual migration to 1.21 

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/gstlal-feedstock#28]
### Comment:

I noticed that the bot previously failed to migrate to gstreamer 1.21

You'll need to debug it and manually push it through.

**Comment by duncanmmacleod** [comment]
@hmaarrfk, the issue was the `gst-python` package pins against gstreamer weren't very good - I fixed that yesterday.

**Comment by hmaarrfk** [comment]
Nice
